version: 0.0
os: linux
files:
  - source: /
    # Change path based on project. Default path is /opt/bitnami/apache/htdocs
    destination: /opt/bitnami/projs/my-tasks
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300